{{ config(materialized='view', tags=['staging']) }}

select
    id,
    version,
    created_at,
    updated_at,
    crash_date::timestamp without time zone as crash_date,
    nullif(trim(crash_time), '') as crash_time,
    nullif(trim(borough), '') as borough,
    nullif(trim(zip_code), '') as zip_code,
    latitude::double precision as latitude,
    longitude::double precision as longitude,
    nullif(trim(location), '') as location,
    nullif(trim(on_street_name), '') as on_street_name,
    nullif(trim(off_street_name), '') as off_street_name,
    nullif(trim(cross_street_name), '') as cross_street_name,
    number_of_persons_injured::numeric as number_of_persons_injured,
    number_of_persons_killed::numeric as number_of_persons_killed,
    number_of_pedestrians_injured::numeric as number_of_pedestrians_injured,
    number_of_pedestrians_killed::numeric as number_of_pedestrians_killed,
    number_of_cyclist_injured::numeric as number_of_cyclist_injured,
    number_of_cyclist_killed::numeric as number_of_cyclist_killed,
    number_of_motorist_injured::numeric as number_of_motorist_injured,
    number_of_motorist_killed::numeric as number_of_motorist_killed,
    nullif(trim(contributing_factor_vehicle_1), '') as contributing_factor_vehicle_1,
    nullif(trim(contributing_factor_vehicle_2), '') as contributing_factor_vehicle_2,
    nullif(trim(contributing_factor_vehicle_3), '') as contributing_factor_vehicle_3,
    nullif(trim(contributing_factor_vehicle_4), '') as contributing_factor_vehicle_4,
    nullif(trim(contributing_factor_vehicle_5), '') as contributing_factor_vehicle_5,
    collision_id::bigint as collision_id,
    nullif(trim(vehicle_type_code1), '') as vehicle_type_code1,
    nullif(trim(vehicle_type_code2), '') as vehicle_type_code2,
    nullif(trim(vehicle_type_code_3), '') as vehicle_type_code_3,
    nullif(trim(vehicle_type_code_4), '') as vehicle_type_code_4,
    nullif(trim(vehicle_type_code_5), '') as vehicle_type_code_5,
    ingested_at
from {{ source('raw', 'crash_data') }}
