{{ config(materialized='view', tags=['staging']) }}

select
    id,
    version,
    created_at,
    updated_at,
    nullif(trim(segmentid), '') as segmentid,
    nullif(trim(bikeid), '') as bikeid,
    nullif(trim(prevbikeid), '') as prevbikeid,
    nullif(trim(status), '') as status,
    nullif(trim(boro), '') as boro,
    nullif(trim(street), '') as street,
    nullif(trim(fromstreet), '') as fromstreet,
    nullif(trim(tostreet), '') as tostreet,
    nullif(trim(onoffst), '') as onoffst,
    nullif(trim(facilitycl), '') as facilitycl,
    nullif(trim(allclasses), '') as allclasses,
    nullif(trim(bikedir), '') as bikedir,
    lanecount::numeric as lanecount,
    nullif(trim(ft_facilit), '') as ft_facilit,
    nullif(trim(tf_facilit), '') as tf_facilit,
    nullif(trim(ft2facilit), '') as ft2facilit,
    nullif(trim(tf2facilit), '') as tf2facilit,
    nullif(trim(instdate), '') as instdate,
    nullif(trim(ret_date), '') as ret_date,
    nullif(trim(grnwy), '') as grnwy,
    nullif(trim(gwsystem), '') as gwsystem,
    nullif(trim(gwsys2), '') as gwsys2,
    nullif(trim(spur), '') as spur,
    nullif(trim(gwyjuris), '') as gwyjuris,
    geometry,
    ingested_at
from {{ source('raw', 'bike_route_data') }}
